services:
  - type: web
    name: dropandshop-ml-api
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app.app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PYTHONPATH
        value: . 